import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "../globals.css";
import MenuBar from "../components/menu";
import SearchBar from "../components/search-bar";
import getSession from "@/lib/session";
import { notFound } from "next/navigation";
import db from "@/lib/db";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

async function getUserName() {
  const session = await getSession();
  if (!session.id) {
    notFound();
  } else {
    const user = await db.user.findUnique({
      where: {
        id: session.id,
      },
      select: {
        username: true,
      },
    });
    return user?.username;
  }
}

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const username = await getUserName();
  return (
    <html lang="en">
      <body
        className={`${inter.className} bg-neutral-100 text-black max-w-screen-sm mx-auto`}
      >
        <div className="flex flex-col items-center w-full">
          <SearchBar />
          {children}
          <MenuBar username={username!} />
        </div>
      </body>
    </html>
  );
}
